# Generated by Django 5.0.3 on 2024-05-22 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campoformulario',
            name='formulario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campos', to='surveys.formulario'),
        ),
        migrations.AddField(
            model_name='opcioncampoformulario',
            name='campoFormulario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opciones', to='surveys.campoformulario'),
        ),
        migrations.AddField(
            model_name='respuestaformulario',
            name='campoFormulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='surveys.campoformulario'),
        ),
        migrations.AddField(
            model_name='respuestaformulario',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campoformulario',
            name='tipoPregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.tipopregunta'),
        ),
    ]
