# Generated by Django 5.0.3 on 2024-05-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_campoformulario_id_alter_formulario_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipopregunta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
