# Generated by Django 5.0.3 on 2025-05-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_respuestaformulario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaformulario',
            name='anon_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
